name: Publish Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build
          python3 -m pip install setuptools wheel
          python3 -m pip install --upgrade twine

      - name: Build Package
        run: |
          python3 -m build

      - name: Publish Package
        run: |
          python3 -m twine upload --password ${{secrets.PYPI_PASSWORD}} dist/*
